---
title: "Identification of Latent Structure in Spatio-Temporal Models"
author: 
  - Nick Clark, United States Military Academy
  - Krista Watts, United States Military Academy  
output: 
  ioslides_presentation:
    incremental: false
    widescreen: true
---

# The Devil's in the dependency!

## Goals of Statistical Models

* Inference - Learn about the underlying data generating mechanism

* Prediction - Use model to predict future observations

* Real world it isn't always so cut and dry

## Modeling of Violence

* 2017 National Institute of Justice competition

* Data driven approach and process driven approaches both used successfully

* Does it matter? Can we differentiate between the two processes?

## Basics

$Y$ is a Poisson process defined on a space-time set $s_i \times t$ with an intensity function for all bounded $B \in S$ given by $\lambda(s_i,t) =  \int_{s_i \times t} \rho (\zeta) d\zeta$

* Informally - terrorism or criminal events arising at higher rates in regions of high intensity and lower rates in regions of lower intensity. 

* How do we structure intensity field?


## Hawkes Process

* Self-exciting process, intensity field is increased by previous observations

* Motivated by Partial Differential Equation similar to reaction diffusion equation

$$
\lambda(s_i,t) = \mu(s_i,t) + \sum_{k: t_k < t} g(t-t_k, |s_i - s_k|)$$


$$
    g(t-t_k,|s_i-s_k|) = \lambda \exp(-\lambda (t-t_k))\frac{1}{2\sigma^2} \exp(-||s_i-s_j|| \frac{1}{2\sigma^2})$$
    
    

## Log Gaussian Cox Process

* Place spatio-temporal structure in an unobserved latent Gaussian process

$$  Z(A) \sim \mbox{Po}\left(\int_A \lambda(s_i,t) d(s_i) dt\right)$$

$$     \log(\lambda) \sim MVN (\mu,\Sigma(\theta))$$

* Assume a sparse spatial precision matrix and a sparse temporal precision matrix



$$\Sigma_{s,t}^{-1} = \Sigma_t(\theta)^{-1} \otimes \Sigma_{s}(\theta)^{-1}$$


# So does any of this matter?

## Posterior Predictive Checks

* How do we determine if a model is appropriate? $\chi^2$ GOF not an option...

* Can a fit model replicate key data characteristics?

* Compare the distribution of a given statistic of our data, $T(y)$ with the same statistic calculated from the posterior distribution of data simulated from our fitted model, $T(y_{rep}|y)$

* What statistic to use?

## Ripley's K

* Quantifies the expected number of additional points within a set distance from another point over what is expected

* High values of Ripley's K mean there is substantial clustering in the data, whereas low values means the data are more dispersed than what would be expected

* Does not necessarily uniquely define a distribution

* Does it in our case?



## Simulation

* Doing what Nick says

## Results

## Conclusion
